# Generated by Django 4.1 on 2022-08-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='watermarked_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
