# Generated by Django 4.1 on 2022-08-24 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_image_watermarked_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='watermarked_url',
        ),
    ]
